### ISSUE TITLE
Rename build directory to support bazel builds?

### ISSUE THREAD

**Issue by Lunarsong** [nigels-com/glew#113]
[Bazel](bazel.io) is a build system by Google. Currently it fails building glew because of a conflicting filename. Issue: https://github.com/bazelbuild/bazel/issues/2010

Suggesting quick fix to rename the build folder (-> make?) to avoid the conflict.

**Comment by nigels-com** [comment]
Bazel is beta.  Requiring exclusive use of a directory named build seems like a fail, on the face of it.

**Comment by Lunarsong** [comment]
Slightly, yes :) 

I made a local fork and renamed the build folder there, so that works for me, however it'd be nice to support it for everyone also. Bazel is *really* nice!
https://github.com/Lunarsong/glew

By the way, seems like some files are missing on the GitHub repo when comparing to the sourceforge .zip file. glew.c and others. This is making builds fail when following documentation.

**Comment by nigels-com** [comment]
Fair enough.  I've gotten sceptical of cmake.  It does a good job for the most part, but I really dislike the maintenance.  I was impressed with ninja, so I do wish Bazel every success.   I need to update the readme to make it more explicit about using a release snapshot, rather than building from scratch from the git repository.  Someone offered/threatened to maintain a git repo of the GLEW generated sources, but I don't know if that's been maintained over time.

**Comment by undisputed-seraphim** [comment]
I haven't encountered any problems with cmake yet, but then again I've mostly stuck to safe toolchains like VS2015 and Make with GCC on Ubuntu and Debian.

**Comment by hulkholden** [comment]
I think the underlying issue is resolved now - Bazel supports build files named BUILD.bazel, so there's no need to rename the build/ dir.

**Comment by nigels-com** [comment]
That's good news, do you have a Bazel build you'd be interested in contributing?  (I need a story to fend off the cmake folks)
